name: Deploy Blazor Webassembly App

env:
  PROJECT_NAME: NBADatabase
  REPO_NAME: ${{ github.event.repository.name }} 

on:
  push: 
    branches:
      - main
  workflow_dispatch: 
  
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3 
    
    - name: Setup .NET SDK 
      uses: actions/setup-dotnet@v3.0.3 
      with:
        dotnet-version: | 
            6.0.X
            7.0.X
            
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools 

    - name: Publish .NET Project
      run: dotnet publish $PROJECT_NAME/$PROJECT_NAME.csproj -c Release -p:RunAOTCompilation=true -o release --nologo
      
    - name: Change base tag
      working-directory: release/wwwroot
      run: |
        find . -name "*.html" | while read htmlFile; do
            #cambia \ del href del index al repositorio
            sed -i 's/<base href="\/"/<base href="\/${{ env.REPO_NAME }}\/"/g' $htmlFile
        done
  
    - name: Fix service-worker-assets.js hashes
      working-directory: release/wwwroot
      run: |
        jsFile=$(<service-worker-assets.js)
        # remove JavaScript from contents so it can be interpreted as JSON
        json=$(echo "$jsFile" | sed "s/self.assetsManifest = //g" | sed "s/;//g")
        # grab the assets JSON array
        assets=$(echo "$json" | jq '.assets[]' -c)
        for asset in $assets
        do
          oldHash=$(echo "$asset" | jq '.hash')
          #remove leading and trailing quotes
          oldHash="${oldHash:1:-1}"
          path=$(echo "$asset" | jq '.url')
          #remove leading and trailing quotes
          path="${path:1:-1}"
          newHash="sha256-$(openssl dgst -sha256 -binary $path | openssl base64 -A)"
          
          if [ $oldHash != $newHash ]; then
            # escape slashes for json
            oldHash=$(echo "$oldHash" | sed 's;/;\\/;g')
            newHash=$(echo "$newHash" | sed 's;/;\\/;g')
            echo "Updating hash for $path from $oldHash to $newHash"
            # escape slashes second time for sed
            oldHash=$(echo "$oldHash" | sed 's;/;\\/;g')
            jsFile=$(echo -n "$jsFile" | sed "s;$oldHash;$newHash;g")
          fi
        done
        echo -n "$jsFile" > service-worker-assets.js

    - name: copy index.html to 404.html 
      run: cp release/wwwroot/index.html release/wwwroot/404.html 

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll #lo crea porque lo necesita github
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
